import { C } from "./constants";

// ── WORKOUT DATA ──────────────────────────────────────────────────────────────
export const WORKOUTS = {
  W1:{ label:"Workout 1", sub:"Upper Strength + Power", color:C.W1,
    exercises:[
      {name:"Push Press",type:"Barbell",sets:4,reps:"4",rest:"2 min",kg:true},
      {name:"Bench Press",type:"Barbell",sets:4,reps:"5–6",rest:"2–3 min",kg:true},
      {name:"Assisted Pull-Up Machine",type:"Machine",sets:4,reps:"6–8",rest:"2 min",kg:true},
      {name:"Barbell Rows",type:"Barbell",sets:3,reps:"8",rest:"90 sec",kg:true},
      {name:"Landmine Rotational Press",type:"Barbell",sets:3,reps:"6/side",rest:"90 sec",kg:true},
      {name:"Face Pulls",type:"Cable",sets:3,reps:"15",rest:"45 sec",kg:true},
      {name:"Farmer Carries",type:"Dumbbell",sets:3,reps:"35m",rest:"90 sec",kg:true},
      {name:"EZ Bar Bicep Curl",type:"Aesthetic",sets:3,reps:"10",rest:"60 sec",kg:true},
      {name:"Tricep Pushdown",type:"Aesthetic",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Lateral Raise",type:"Aesthetic",sets:3,reps:"15",rest:"45 sec",kg:true},
      {name:"Dumbbell Shrug",type:"Aesthetic",sets:3,reps:"15",rest:"45 sec",kg:true},
      {name:"Back Extension",type:"Core",sets:3,reps:"12",rest:"60 sec",kg:false},
      {name:"Bird Dog",type:"Core",sets:3,reps:"8/side",rest:"60 sec",kg:false},
    ]},
  W2:{ label:"Workout 2", sub:"Lower Force + Braking", color:C.W2,
    exercises:[
      {name:"Box Jump — Step Down",type:"Explosive",sets:4,reps:"4",rest:"2 min",kg:false},
      {name:"Back Squat",type:"Barbell",sets:4,reps:"5",rest:"3 min",kg:true},
      {name:"Romanian Deadlift",type:"Barbell",sets:3,reps:"6",rest:"2 min",kg:true},
      {name:"Bulgarian Split Squat",type:"Dumbbell",sets:3,reps:"8/leg",rest:"90 sec",kg:true},
      {name:"Hip Abductor Machine",type:"Machine",sets:3,reps:"15",rest:"60 sec",kg:true},
      {name:"Hip Adductor Machine",type:"Machine",sets:3,reps:"15",rest:"60 sec",kg:true},
      {name:"Snap Down — Stick",type:"Explosive",sets:3,reps:"5",rest:"Full",kg:false},
      {name:"Tibialis Raises",type:"Bodyweight",sets:3,reps:"15–20",rest:"45 sec",kg:false},
      {name:"Leg Extension Machine",type:"Machine",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Standing Calf Raise",type:"Aesthetic",sets:4,reps:"15",rest:"45 sec",kg:true},
      {name:"Leg Curl Machine",type:"Aesthetic",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Dead Bug",type:"Core",sets:3,reps:"8/side",rest:"60 sec",kg:false},
      {name:"Pallof Press",type:"Core",sets:3,reps:"10/side",rest:"60 sec",kg:true},
    ]},
  W3:{ label:"Workout 3", sub:"Lower Elasticity + Reactivity", color:C.W3,
    exercises:[
      {name:"Approach Verticals",type:"Explosive",sets:7,reps:"Max",rest:"Full",kg:false},
      {name:"Linear Pogos",type:"Explosive",sets:3,reps:"20",rest:"60 sec",kg:false},
      {name:"Lateral Bounds",type:"Explosive",sets:3,reps:"8/side",rest:"90 sec",kg:false},
      {name:"Goblet Squat",type:"Dumbbell",sets:3,reps:"5–6",rest:"2 min",kg:true},
      {name:"Walking Lunges",type:"Dumbbell",sets:3,reps:"10/leg",rest:"90 sec",kg:true},
      {name:"Single Leg RDL",type:"Dumbbell",sets:3,reps:"6/leg",rest:"90 sec",kg:true},
      {name:"Split Squat Iso Hold",type:"Bodyweight",sets:2,reps:"35–45 sec",rest:"Full",kg:false},
      {name:"Slow Calf Raises — Single Leg",type:"Bodyweight",sets:3,reps:"12",rest:"45 sec",kg:false},
      {name:"Seated Calf Raise",type:"Aesthetic",sets:3,reps:"20",rest:"45 sec",kg:true},
      {name:"Hollow Body Hold",type:"Core",sets:2,reps:"20 sec",rest:"30 sec",kg:false},
      {name:"Front Plank",type:"Core",sets:1,reps:"45 sec",rest:"30 sec",kg:false},
      {name:"Leg Drops",type:"Core",sets:2,reps:"10",rest:"30 sec",kg:false},
    ]},
  W4:{ label:"Workout 4", sub:"Upper Structure + Aesthetics", color:C.W4,
    exercises:[
      {name:"Incline DB Press",type:"Dumbbell",sets:3,reps:"8–10",rest:"2 min",kg:true},
      {name:"Assisted Pull-Up — Negatives",type:"Machine",sets:4,reps:"5–6",rest:"2 min",kg:true},
      {name:"Lat Pulldown Machine",type:"Machine",sets:3,reps:"10–12",rest:"90 sec",kg:true},
      {name:"Seated Row Machine",type:"Machine",sets:3,reps:"10–12",rest:"90 sec",kg:true},
      {name:"Shoulder Press Machine",type:"Machine",sets:3,reps:"10–12",rest:"90 sec",kg:true},
      {name:"Single Arm DB Press",type:"Dumbbell",sets:3,reps:"8/side",rest:"90 sec",kg:true},
      {name:"Face Pulls",type:"Cable",sets:3,reps:"15",rest:"45 sec",kg:true},
      {name:"Dead Hangs",type:"Bodyweight",sets:3,reps:"30–45 sec",rest:"Full",kg:false},
      {name:"Straight Arm Pulldown",type:"Aesthetic",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Cable Fly",type:"Aesthetic",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Rear Delt Fly",type:"Aesthetic",sets:3,reps:"15",rest:"45 sec",kg:true},
      {name:"Hammer Curl",type:"Aesthetic",sets:3,reps:"10/side",rest:"60 sec",kg:true},
      {name:"Overhead Tricep Extension",type:"Aesthetic",sets:3,reps:"12",rest:"60 sec",kg:true},
      {name:"Med Ball Rotational Throw",type:"Core",sets:4,reps:"6/side",rest:"Full",kg:false},
      {name:"Cable Woodchop",type:"Core",sets:3,reps:"8/side",rest:"60 sec",kg:true},
      {name:"Seated Russian Twist",type:"Core",sets:3,reps:"10/side",rest:"60 sec",kg:true},
    ]},
};
